# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    stdlib: "puppetlabs/stdlib"
  repositories:
    provision: 'https://github.com/puppetlabs/provision'
    puppet_agent: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
    translate: 'https://github.com/puppetlabs/puppetlabs-translate.git'
