name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release
    uses: voxpupuli/gha-puppet/.github/workflows/release.yml@v2
    with:
      allowed_owner: 'icann-dns'
    secrets:
      username: ${{ secrets.PUPPET_FORGE_USERNAME }}
      api_key: ${{ secrets.PUPPET_FORGE_API_KEY }}

  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub release
        uses: voxpupuli/gha-create-a-github-release@v1
